import type { NextPage } from 'next';
import Head from 'next/head';
import Grid from '@mui/material/Grid';
import { styled } from '@mui/material/styles';
import Paper from '@mui/material/Paper';
import { Box, Button } from '@mui/material';
import WhatshotIcon from '@mui/icons-material/Whatshot';
import AccessTimeIcon from '@mui/icons-material/AccessTime';
import CallMissedOutgoingIcon from '@mui/icons-material/CallMissedOutgoing';
import FormatListBulletedIcon from '@mui/icons-material/FormatListBulleted';

import Header from '../components/Header';

const Item = styled(Paper)(({ theme }) => ({
  ...theme.typography.body2,
  padding: theme.spacing(1),
  textAlign: 'center',
  color: theme.palette.text.secondary,
}));

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>KZJournal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Mukta:wght@200;300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header />

      {/* Layout  */}
      <Grid container spacing={3} style={{ maxWidth: '1200px', margin: '0 auto' }}>
        <Grid item xs>
          Sidebar
        </Grid>
        <Grid item xs={6} style={{ paddingLeft: 0 }}>
          <Box display="flex" justifyContent="space-between">
            <Button startIcon={<WhatshotIcon />}>Popular</Button>
            <Button startIcon={<AccessTimeIcon />}>Lates</Button>
            <Button startIcon={<CallMissedOutgoingIcon />}>Rating</Button>
            <Button startIcon={<FormatListBulletedIcon />}>Subscriptions</Button>
          </Box>
        </Grid>
        <Grid item xs>
          Comments
        </Grid>
      </Grid>
    </div>
  );
};

export default Home;
